[package]
name = "bevy_toon_shader"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.10", default-features = false, features = [
  "bevy_pbr",
  "bevy_render",
  "bevy_asset",
] }

[dev-dependencies]
bevy = { version = "0.10" }
bevy_egui = "0.20.2"
